# -*- coding: utf-8 -*-
"""pdf_extractor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MznU50swuAEh1VSbn3yhNtUjMVLTftDe

# PDF Text Extractor
"""

#!pip install pypdf

from pypdf import PdfReader
import os

def extract_text_and_metadata_from_pdf(pdf_path):
  """Extracts text and specific metadata (title, author, category, mood) from a PDF file."""
  book_data = [] # List to store dictionaries of book information

  try:
    reader = PdfReader(pdf_path)
    for i, page in enumerate(reader.pages):
      if i > 0: # Skip the first page
        page_text = page.extract_text()
        if page_text:
          lines = page_text.splitlines()
          if len(lines) >= 5: # Ensure there are enough lines for all fields
            title = lines[0].strip()
            author = lines[1].strip()
            category = lines[2].strip()
            mood_tags = lines[3].strip()
            description = "\n".join(lines[4:]).strip() # The rest is the description

            book_data.append({
                'title': title,
                'author': author,
                'category': category,
                'mood_tags': mood_tags,
                'description': description
            })
          elif lines: # Handle pages with less than 5 lines, just store the available text
              book_data.append({
                  'title': lines[0].strip() if len(lines) > 0 else "No Title Found",
                  'author': lines[1].strip() if len(lines) > 1 else "No Author Found",
                  'category': lines[2].strip() if len(lines) > 2 else "No Category Found",
                  'mood_tags': lines[3].strip() if len(lines) > 3 else "No Mood Tags Found",
                  'description': "\n".join(lines[4:]).strip() if len(lines) > 4 else "No Description Found"
              })


    print(f"Extracted data for {len(book_data)} books.")
  except Exception as e:
    print(f"Error reading {pdf_path}: {e}")
    return [] # Return empty list in case of error

  return book_data